### ISSUE TITLE
Stevie's To-Do List

### ISSUE THREAD

**Issue by steviegt6** [Steviegt6/steviegt6.github.io#4]
# Stevie's To-Do List

### Basic Introduction

Hey, everyone. This is a handy to-do list of everything I am trying to get done with my website!

### Definitions

[I] = Important
[IP] = In Progress
[NI] = Not Important
[UN] = Unnecessary

### List

And so the list begins.

* Ideas [I]
* Learn JavaScript [NI]
* Make main page [IP]
* Better CS [NI]
* Clearner Code [NI]

**Comment by unblockedgamess** [comment]
hi how can I reach you?

**Comment by steviegt6** [comment]
Contact me on Discord. (convicted tomatophile#9616)

**Comment by unblockedgamess** [comment]
I cannot send a direct message. do you use Skype?

**Comment by steviegt6** [comment]
> 
> 
> I cannot send a direct message. do you use Skype?

No, I do not. Just add me on Discord or join me server here: [Discord](discord.gg/qrZ4Bpz)
